### ISSUE TITLE
Why adding payment option?

### ISSUE THREAD

**Issue by craftercis** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#38]
Hello!

This may be a dumb question but why do we need to add a payment option to our accounts? I can use ChatGPT 3.5 free on their website. Is it because we use an API?

If I add a payment option to my account, how likely and how much do I need to pay? I want to use GPT 3.5

EDIT:
I now see it is because of the API. Then I only want to know what the minimum amount of cents/euros is when they are charging me.

**Comment by MichielvanBeers** [comment]
Hi @craftercis, definitely not a dumb question :)! 

You're indeed correct that it is because of the use of the API. An advantage is that OpenAI doesn't store the data that you send to the API, whereas the free web version of ChatGPT does do that.

Moneywise it depends on your usage. The gpt-3.5-turbo model (same as with the free online version ChatGPT) is $0.002 / 1K tokens, whereas 1 token is ~1.5 words. So for a dollar or so, you can get a lot of queries. Keep in mind that token calculation also takes into account your input tokens. I've listed some additional documentation below. Good luck!

* Token pricing: https://openai.com/pricing
* Token calculator: https://platform.openai.com/tokenizer
